-- local pickers = require("telescope.pickers")
-- local finders = require("telescope.finders")
-- local actions = require("telescope.actions")
-- local config = require("telescope.config").values
--
-- local M = {}
--
-- M.print_stuff = function(opts)
--   pickers
--     .new(opts, {
--       finder = finders.new_table({
--         results = {
--           { name = "test1", value = { 1, 2, 3, 4 } },
--           { name = "test2", value = { 1, 2, 3, 4 } },
--           { name = "test2", value = { 1, 2, 3, 4 } },
--           { name = "test3", value = { 1, 2, 3, 4 } },
--           { name = "test2", value = { 1, 2, 3, 4 } },
--           { name = "test4", value = { 1, 2, 3, 4 } },
--         },
--       }),
--       sorter = config.generic_sorter(opts),
--     })
--     :find()
-- end
--
-- -- M.print_stuff()
--
-- return M
